language: python
group: travis_latest

git:
  depth: 25
  quiet: true

python:
- 3.6

os:
- linux

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libfftw3-dev

install: pip install -e .[tests]

script:
- pytest -rsv
- flake8
- mypy .

after_success:
- pytest --cov
- coveralls
