language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libfftw3-dev

install: pip install -e .

script: pytest -v

after_success: 
  - coverage run tests/test_all.py
  - coveralls

