language: python
group: travis_latest

git:
  depth: 25
  quiet: true

os:
- linux

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libfftw3-dev

install: pip install -e .[tests]

script:
- pytest
- flake8
- mypy .
