language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libfftw3-dev

before_install:
    - pip -q install coveralls
    # for pip < 9.1
    - pip -q install numpy

install: pip install -e .

script: coverage run tests/test.py -v

after_success: coveralls

